Lock version of generator, test failing
adobe/asset-compute-integration-tests pull request #42
Opened 2024-01-12 22:15 UTC by purplecabbage

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes # (issue)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-01-17 21:33 UTC, tmathern requested changes

2024-01-17 21:33 UTC, tmathern commented on test/index.test.js
> +    it.skip("should install version 8.3.0 of aio-cli and run developer experience", async function() {
Is this version unsupported now?

2024-01-17 21:33 UTC, tmathern commented on test/index.test.js
> +    it.skip("should install version 7.1.0 of aio-cli and run developer experience", async function() {
Is this version unsupported now?
If so, rather than skip we should remove it.

2024-01-26 17:31 UTC, tmathern commented on test/index.test.js
> +            npm install -g @adobe/aio-cli@9.4.1
If we lock, it's not installing latest anymore...

2024-01-30 03:13 UTC, purplecabbage commented
Please merge this and we will deal with adding tests for latest/latest in another pr.
We have daily tests that are failing until this is merged.

2024-01-30 17:19 UTC, sudheendrakatikar approved these changes

2024-01-30 17:24 UTC, tmathern approved these changes

2024-01-30 17:25 UTC, tmathern commented
> Please merge this and we will deal with adding tests for latest/latest in another pr. We have daily tests that are failing until this is merged.

We'll remind you of that ;).
PR is approved.

2024-01-30 17:55 UTC, pheenomenon commented
@purplecabbage Is there a followup jira you have to fix on latest aio version.

2024-01-31 14:03 UTC, shazron commented
@pheenomenon added https://jira.corp.adobe.com/browse/ACNA-2655. 

@tmathern @pheenomenon Can this be squashed/merged in so I can rebase off it for PR #40 ? Thanks!

2024-01-31 20:49 UTC, merged